logger:
  dir: ./logs
  is_debug: false
  is_development: true

grpc:
  port: 50051

repository:
  port: 5432
  host: auth-database
  user: pq_user
  password: superpass
  database: postgres

jwt:
  access-secret: <very-secret-secret>
  refresh-secret: <so-very-secret-secret>
  ttl:
    access-ttl: "2h"
    refresh-ttl: "24h"